export const catagory_options = [
  "Facebook",
  "Twitter",
  "Instagram",
  "Sign Up",
  "Search / Click",
  "Promotion",
  "Telegram",
  "Mobile Application",
  "Share",
  "Gmail Account",
  "Comment",
  "Visitor",
  "Computer Programs",
  "Write an Article",
  "Answers",
  "Views",
  "Others",
  "Tik-tok",
  "Refer Program",
  "Survey",
  "Facebook-Invite",
  "Review",
  "Ads Click",
  "YouTube / Toffe",
  "Assigenment",
  "Story",
  "Typing",
  "Edit",
  "Linkedin",
  "Reddit",
  "Medium",
  "Discord",
  "Graphics Design",
  "Blog",
  "Website",
  "Kyc Submit",
  "Reel / Short",
  "Whats-App",
  "App Pre Tester",
  "Airdrop Join",
  "Need Follower",
  "Quora",
  "Back Link",
];

export const regions = [
  "International",
  "Asia",
  "USA & Western",
  "Africa",
  "Europe West",
  "Muslim Countries",
  "Europe East",
  "Latin America",
];
