export const keywords = [
  // Social Media Engagement
  "watch video",
  "like Facebook post",
  "comment on Instagram",
  "follow on Twitter",
  "subscribe on YouTube",
  "retweet/post on Twitter",
  "share LinkedIn update",
  "like LinkedIn post",
  "add to Pinterest board",
  "pin image",
  "upvote Reddit post",
  "comment Reddit thread",
  "join Facebook group",
  "like Snapchat story",
  "react on TikTok",
  "follow TikTok account",
  "comment YouTube video",
  "like YouTube video",
  "add Instagram story view",
  "watch Instagram reel",
  "share Instagram reel",
  "like Facebook page",
  "check in on Facebook",
  "save Instagram post",
  "send friend request",
  "reply to tweet",
  "share tweet",
  "tag a friend Instagram",
  "mention brand on social",
  "join Discord server",

  // Content Consumption
  "read blog post",
  "watch tutorial video",
  "finish an article",
  "read newsletter",
  "play audio clip",
  "listen to podcast",
  "complete survey",
  "scroll webpage",
  "read product review",
  "view image gallery",
  "watch webinar",
  "read FAQ page",
  "scan PDF",
  "open email",
  "preview presentation",
  "read case study",
  "download ebook",
  "browse catalog",
  "view landing page",
  "click banner",

  // Product & Brand Tasks
  "rate product 1–5",
  "write rating",
  "leave product review",
  "upload product picture",
  "recommend product",
  "share product link",
  "use discount code",
  "add item to cart",
  "wishlist product",
  "share wishlist",

  // App & Software Tasks
  "install app",
  "open app",
  "create account",
  "enable notifications",
  "set profile picture",
  "update bio",
  "complete app tutorial",
  "change app setting",
  "connect social account",
  "link email account",

  // Feedback & Surveys
  "answer multiple-choice",
  "write 50-word review",
  "complete 1-min quiz",
  "rate experience",
  "select preference",
  "choose favorite option",
  "check grammar",
  "proofread text",
  "summarize content",
  "give star rating",

  // Email & Communication
  "open email",
  "click email link",
  "reply to email",
  "forward email",
  "unsubscribe",
  "verify email address",
  "send thank-you note",
  "rate email",
  "tag contact",
  "annotate email",

  // Mention, Tag & Share
  "mention brand",
  "tag friend",
  "post testimonial",
  "share personal story",
  "share quote",
  "repost content",
  "shout-out brand",
  "pin tweet",
  "embed video",
  "mention in forum",

  // Search & Discovery
  "search keyword",
  "bookmark result",
  "filter category",
  "sort list",
  "click search result",
  "view profile",
  "expand bio",
  "check credentials",
  "map location",
  "examine details",

  // Content Creation
  "write caption",
  "title post",
  "leave comment",
  "tag image",
  "record voice note",
  "upload image",
  "design graphic",
  "pick emoji",
  "choose hashtag",
  "write tweet",

  // Brainstorming & Opinions
  "suggest idea",
  "vote poll",
  "rank options",
  "choose top 3",
  "rate feature",
  "pick challenge",
  "select design",
  "rate prototype",
  "share suggestion",
  "describe experience",

  // Misc Small Tasks
  "verify spelling",
  "check link",
  "scan message",
  "tag category",
  "flag content",
  "accept terms",
  "fill field",
  "complete form",
  "choose icon",
  "select color",

  // Social Engagement Extended
  "like TikTok video",
  "comment TikTok clip",
  "follow Snapchat account",
  "share Pinterest pin",
  "comment on LinkedIn article",
  "react on Instagram post",
  "reply LinkedIn comment",
  "reshare Facebook story",
  "message Instagram account",
  "view Facebook live",
  "watch LinkedIn live",
  "recommend group",
  "endorse skill LinkedIn",
  "applaud on Medium",
  "follow Medium publication",
  "clap article",
  "review Quora answer",
  "upvote Quora question",
  "share Quora answer",
  "comment Periscope",
  "subscribe podcast",
  "share SoundCloud track",

  // Content & Feedback Extended
  "like article",
  "rate blog",
  "review whitepaper",
  "open case study",
  "download guide",
  "highlight text",
  "annotate PDF",
  "complete poll",
  "choose infographic",
  "share infographic",

  // Creation & Tagging Extended
  "tag photo",
  "add alt-text",
  "choose thumbnail",
  "write metadata",
  "pick filter",
  "design meme",
  "tag GIF",
  "submit cartoon",
  "write script",
  "record snippet",

  // Surveys & Research Extended
  "choose top benefit",
  "rank product features",
  "answer satisfaction",
  "give feedback audio",
  "select best image",
  "rate video quality",

  // Organization & Cleanup
  "delete duplicate",
  "sort files",
  "tag folder",
  "mark read",
  "archive post",
  "flag notification",
  "sync cloud folder",

  // Simple Site/App Tasks
  "update password",
  "set privacy",
  "toggle dark mode",
  "enable location",
  "adjust font size",
  "change theme",
];
